name: Go api

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Go
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --web-renderer=html --no-tree-shake-icons --release

      - name: Deploy
        run: |
          cd build/web
          git init
          git config --global user.email joaopedrorafael19@gmail.com
          git config --global user.name JoaoRafa19
          git status
          git remote add origin https://${{secrets.token}}@github.com/JoaoRafa19/JoaoRafa19.github.io.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f